[params]
  [params.favicon]
    theme = "#ffffff"
    background = "#ffffff"
    [params.favicon.webmanifest]
      fingerprint = false

[module]
  [module.hugoVersion]
    min = "0.116.0"

  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
